### ISSUE TITLE
mf_extract doesn't work

### ISSUE THREAD

**Issue by 1u** [gadicc/meteor-messageformat#77]
On a system with npm package still globaly installed:
```
project_dir$ mf_extract

module.js:340
    throw err;
          ^
Error: Cannot find module '../.npm/package/node_modules/walk'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/fritz/.meteorite/packages/messageformat/gadicohen/meteor-messageformat/9152409d83d402bf796df812f63af5ee0977ae2b/cli/mf_extract.js:4:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```
 aswell as on a fresh system without manualy installing packages
```
project_dir$ nodejs ~/.meteor/packages/gadicohen\:messageformat/0.0.46/os/packages/gadicohen\:messageformat/cli/mf_extract.js 
path.js:360
        throw new TypeError('Arguments to path.join must be strings');
              ^
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at Object.<anonymous> (/home/renate/.meteor/packages/gadicohen:messageformat/.0.0.46.8tz88f++os+web.browser+web.cordova/os/packages/gadicohen:messageformat/cli/mf_extract.js:10:28)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```
messageformat 0.0.46, meteor 1.1.3  
for project https://github.com/schuel/hmmm

ps: and thanks so much for the great work gadi!

**Comment by 1024kilobyte** [comment]
Did you find a solution to the problem. It seems I ran into the same one.

```
$ meteor create testapp && cd testapp
testapp: created.                             

To run your new app:                          
  cd testapp                                  
  meteor                                      
$ meteor add gadicohen:messageformat
                                              
Changes to your project's package version selections:
                                              
gadicohen:headers           added, version 0.0.25
gadicohen:messageformat     added, version 0.0.46
iron:controller             added, version 1.0.7
iron:core                   added, version 1.0.7
iron:dynamic-template       added, version 1.0.7
iron:layout                 added, version 1.0.7
iron:location               added, version 1.0.7
iron:middleware-stack       added, version 1.0.7
iron:router                 added, version 1.0.7
iron:url                    added, version 1.0.7
meteorhacks:inject-initial  added, version 1.0.2

                                              
gadicohen:messageformat: MessageFormat support, the Meteor way
$ mf_extract                 
Using /Users/1024kilobyte/.meteor/packages/gadicohen:messageformat/0.0.46/os/packages/gadicohen:messageformat/cli/mf_extract.js

module.js:340
    throw err;
          ^
Error: Cannot find module '/Users/1024kilobyte/.meteor/packages/gadicohen:messageformat/0.0.46/os/packages/gadicohen:messageformat/cli/mf_extract.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

```
$ npm list meteor-messageformat -g
/usr/local/lib
└── meteor-messageformat@0.0.6 
```

The reason seems to be that meteor saves the package with the colon replaced to underscore in:

.meteor/packages/gadicohen_messageformat

And while writing I solved the issue for me with a simple symlink (from the packages folder):

$ ln -s gadicohen_messageformat/ gadicohen\:messageformat

Now working great, thanks for the package!

**Comment by 1u** [comment]
two friends saved it with symlinks too

**Comment by 1u** [comment]
first this:  `~/.meteor/packages/$ mv gadicohen:messageformat gadicohen:messageformat_renamed ` ?

    ~/.meteor/packages/$ ln -s gadicohen_messageformat/ gadicohen:messageformat

I tried all the combinations, and it didnt work:

    Using [project-dir]/packages/messageformat/cli/mf_extract.js
    module.js:340
        throw err;
              ^
    Error: Cannot find module '../.npm/package/node_modules/walk'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)

$ which mf_extract: `/usr/local/bin/mf_extract`  
and there's the file... with this:

    if (!cliPath) {
        var versions = loadVersions(projRoot);

        if (!versions) {
                // In Meteor < 0.9, if it's not in package directory, it's not installed
                console.log("Error: Can't find " + cliPath + "\n"
                        + "Are you sure messageformat is installed in this project?");
                process.exit(1);
        }

        for (var name, i=0; i < possibleNames.length; i++) {
                name = possibleNames[i];
                if (versions[name]) {
                        cliPath = path.join(process.env.HOME, '.meteor', 'packages', name,
                                versions[name], 'os', 'packages', name, 'cli', 'mf_extract.js');
                        npmBuild = path.join(process.env.HOME, '.meteor', 'packages', name,
                                versions[name], 'npm', 'node_modules');
                        break;
                }
        }

**Comment by gadicc** [comment]
Hi all, big apologies on the lack of action on this :(  I had noted that people got it working with symlinks, but @1u in light of your most recent comment I published v0.0.7 of the wrapper now... would you mind to please:

```bash
$ sudo npm install -g meteor-messageformat
```

and see if that fixes the issue finally?  MDG keep changing this but it seems to have settled now, even though it looks a bit weird... it's working with the current version and I tried to look out for further changes in the future and/or potentially older versions.

**Comment by brylie** [comment]
I am getting the following error when running `mf-extract` from the project directory:

```
kpathsea: Running mktexmf extract
! I can't find file `extract'.
<*> extract
```

Steps I took to reproduce (from Meteor project directory):

1. `meteor add adicohen:messageformat`
2. `sudo npm install -g meteor-messageformat`
3. `mf extract` (no underscore)

Additional details:
```bash
$ npm list meteor-messageformat -g
/usr/local/lib
└── meteor-messageformat@0.0.8 
```

```javascript
/* .meteor/versions */
...
gadicohen:headers@0.0.27
gadicohen:messageformat@0.0.50
...
```

**Comment by brylie** [comment]
OK, I just ran `meteor` and then `mf_extract` from a second tab. That seemed to work. This might just be a documentation issue, as it wasn't very clear the proper steps to initialize the project.

**Comment by gadicc** [comment]
Thanks for your contribution to the README.  Made this a little bit clearer.  You figured it out, but yeah, you need to run `meteor` at least once in your project dir before running `mf_extract` (which is one word connected by an underscore).

In general, although I think we've solved everything now, `mf_extract` caused us a lot of grief over the various Meteor releases and different OSes.  In v2 (no ETA yet) we did away with it completely and watch everything automatically for you, so things got a lot easier.

**Comment by 1u** [comment]
I still get the exact same error as in first post (upper one) of this issue
if I'm the only one please ignore :)

I tried:

    $ sudo npm install -g meteor-messageformat

aswell as uninstall and install it localy and globaly

here are the versions:

    .meteor/versions
    gadicohen:headers@0.0.27
    gadicohen:messageformat@0.0.52
    ...    
    meteor@1.1.5
    meteor-platform@1.2.2

and

    $ npm ls -g
    /usr/local/lib
    ├─┬ meteor-messageformat@0.0.8
    │ ├── underscore@1.5.2
    │ └─┬ walk@2.2.1
    │   └─┬ forEachAsync@2.2.1
    │     └── sequence@2.2.1
    ....

lib and bin

    $ which mf_extract 
    /usr/local/bin/mf_extract

**Comment by gadicc** [comment]
No ways, I don't believe it!  Haha I think you may well be the only person but I'd still like to work this out!  Would you mind repasting the error message?  Some of the line numbers would have changed a bit since you first opened the issue.  Everything looks good in all the other stuff you pasted, but for comparison's sake, a fresh install should look like this:

```bash
$ meteor create x && cd x
$ meteor add gadicohen:messageformat
                                                                                
Changes to your project\'s package version selections:
                                              
gadicohen:headers           added, version 0.0.27
gadicohen:messageformat     added, version 0.0.52
meteorhacks:inject-initial  added, version 1.0.2

                                              
gadicohen:messageformat: MessageFormat support, the Meteor way

dragon@dragon:~/tmp/x$ sudo npm install -g meteor-messageformat
[sudo] password for dragon: 
/usr/bin/mf_extract -> /usr/lib/node_modules/meteor-messageformat/mf_extract_wrapper.js
meteor-messageformat@0.0.8 /usr/lib/node_modules/meteor-messageformat
├── underscore@1.5.2
└── walk@2.2.1 (forEachAsync@2.2.1)

dragon@dragon:~/tmp/x$ mf_extract
Using /home/dragon/.meteor/packages/gadicohen_messageformat/0.0.52/os/packages/gadicohen:messageformat/cli/mf_extract.js
Creating ./server directory
```

Note on my system `install -g` installs to `/usr/bin/mf_extract` - you could also double check that it didn't install to two different places and is using the wrong one, or just double check:

```bash
$ md5sum `which mf_extract`
c4aee7b42978b7354817a127ede3f1f6  /usr/bin/mf_extract
```

But I think it's more likely another weird system-specific case which is why I'm happy we're getting rid of mf_extract in v2.

**Comment by 1u** [comment]
:)

I checked the lines before and they where all exactly the same. here they are:

    $ mf_extract 
    Using [Project-dir]/packages/messageformat/cli/mf_extract.js

    module.js:340
    throw err;
          ^
    Error: Cannot find module '../.npm/package/node_modules/walk'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/fritz/.meteorite/packages/messageformat/gadicohen/meteor-messageformat/9152409d83d402bf796df812f63af5ee0977ae2b/cli/mf_extract.js:4:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

exept of course the first line:

    Using [Project-dir: .../hmmm] /packages/messageformat/cli/mf_extract.js

is that the problem then, right?  
on a fresh install it worked fine now.

Hash is congruent:

    $ md5sum `which mf_extract`
    c4aee7b42978b7354817a127ede3f1f6  /usr/local/bin/mf_extract

`$ readlink -f $(which mf_extract)` or `ls -l /usr/local/bin/mf_extract`

    $ md5sum /usr/local/lib/node_modules/meteor-messageformat/mf_extract_wrapper.js
    c4aee7b42978b7354817a127ede3f1f6  /usr/local/lib/node_modules/meteor-messageformat/mf_extract_wrapper.js

all fine right?    
here we go:  
and to be shure: `$ sudo find / -name mf_extract` only finds `/usr/local/bin/mf_extract`  
so: in project dir:

    $ mv packages/messageformat/cli/mf_extract.js packages/messageformat/cli/mf_extract_renamed.js`

then:

    $ mf_extract 
    Using [prjectdir]ls/packages/messageformat/cli/mf_extract.js

    module.js:340
    throw err;
          ^
    Error: Cannot find module '[project-dir]/packages/messageformat/cli/mf_extract.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

further:

    $ which node
    /usr/local/bin/node

    $ /usr/local/bin/node -v
    v0.10.12

seems to be manually installed. system proposes to install nodejs_0.10.25

whatever. if you see the problem right away, tell me. otherwise I'll ask a friend.  
thank you so much  
ps: I like the translation-view much better with TransPreviewTableWidth at 100% than 500%  ;)

**Comment by gadicc** [comment]
Ok wait this is progress!  You're definitely using the latest meteor-messageformat npm release now... in the past I don't think this was the case since you weren't getting that first line.

Just to double check, this isn't a new project / you have run `meteor` at least once in the project dir.

I noticed you're running a local clone of the package, and not installed via meteor's package manager, but this is supported and should still work.  It's weird though that the directory is called "messageformat" and not "gadicohen:messageformat", I can't get it to run like that without modifying `package.js`.  If I did do all that though, it still works... but let me know if you did anything usual here.

Does `project/packages/messageformat/.npm` exist?  Could you show me the output of

```bash
~/projdir$ find packages/messageformat/ -maxdepth 4 ! -regex ".*/\\.git/.*" -regex ".*\\.npm.*" -type f
```

> ps: I like the translation-view much better with TransPreviewTableWidth at 100% than 500% ;)

lol.  I don't know where or how that stuck in.  I had noticed it my side but thought it was a browser issue on my end since I hadn't changed anything and no one had reported anything.  But when I had some time to try "fix my browser" I realized what the problem was.

**Comment by 1u** [comment]
> Just to double check, this isn't a new project / you have run `meteor` at least once in the project dir.

Jep. (and problem consists only in this project dir, everything works fine in new project)

> Does `project/packages/messageformat/.npm` exist?

no:

    ls packages/messageformat/
    cli  History.md  laika  lib  Makefile  mk  package.js  README.md  run_tests.sh  smart.json  website

and no output for your `find...`

probably this will rise more questions than answers, but if there is one answer at least, it's fine. Here we go:

    $ ls -l packages/

    lrwxrwxrwx 1 me me 110 Jul  5  2014 blaze-layout -> ~/.meteorite/packages/blaze-layout/EventedMind/blaze-layout/b40e9b0612329288d75cf52ad14a7da64bb8618f
    lrwxrwxrwx 1 me me  24 Feb 24 22:48 gadicohen:messageformat -> gadicohen_messageformat/
    lrwxrwxrwx 1 me me 105 Jul  5  2014 headers -> ~/.meteorite/packages/headers/gadicohen/meteor-headers/3c09e682895e13c71ca0114baf3c09ee9c507709
    lrwxrwxrwx 1 me me 116 Jul  5  2014 inject-initial -> ~/.meteorite/packages/inject-initial/gadicc/meteor-inject-initial/90f2fbcc5b4bc17fa4d4535f47813e31d86033b4
    lrwxrwxrwx 1 me me 108 Jul  5  2014 iron-router -> ~/.meteorite/packages/iron-router/EventedMind/iron-router/d1ffb3f06ea4c112132b030f2eb1a70b81675ecb
    lrwxrwxrwx 1 me me 117 Jul  5  2014 messageformat -> ~/.meteorite/packages/messageformat/gadicohen/meteor-messageformat/9152409d83d402bf796df812f63af5ee0977ae2b

then I tried punk-rock style:

    mv packages/ packages_renamed

first time fixed it! :lollipop: 
mf_extract works: :smiling_imp: 

    $ mf_extract
    Using ~/.meteor/packages/gadicohen_messageformat/0.0.52/os/packages/gadicohen:messageformat/cli/mf_extract.jse

jfyi:

    ls -hal ~/.meteor/packages/
    drwxr-xr-x   4 me me  4.0K Mär 20 11:14 gadicohen_headers
    drwxr-xr-x   4 me me 4.0K Okt 30 16:29 gadicohen:headers
    drwxr-xr-x   3 me me 4.0K Okt 30 16:29 gadicohen:inject-initial
    drwxr-xr-x   6 me me 4.0K Mär 20 11:14 gadicohen_messageformat
    lrwxrwxrwx   1 me me   24 Feb 24 23:05 gadicohen:messageformat -> gadicohen_messageformat/


(**By the way**) starting up meteor   
hough, this is a nice one: 

    Errors prevented startup:                  
    While building the application:
    error: Symlink cycle detected at packages_renamed/inject-initial/website/packages/inject-initial
    
    ls -l packages_renamed/inject-initial/website/packages/
    lrwxrwxrwx 1 me me  5 Jul  5  2014 inject-initial -> ../..

and a lot more `Unexpected token ILLEGAL` and `bad formatting in HTML template` errors.  
ok, so:  `mv packages_renamed/ /tmp/` respectively for better documentation:

|   `mv packages/ /tmp/`    |
|:--------------------------------------------:|


and everything works fine! never thought it would have been so easy as this single command.


----
ps:

> lol. I don't know where or how that stuck in. 

In order to find out, look up your calendar at Nov 2013   :D   (`blame`)

> I had noticed it my side but thought it was a browser issue on my end since...

thought you have some browser-issue too: so that it shows it "normal" to you :)  
Since ever I thought, that to see the translated strings in the table aswell would be usefull. Some weeks ago I found out that they are supposed to be there, outside the frame somewhere. And exactly last Thursday I inspected the problem with a friend @sbalmer and found the 500%. So I thought, when it was fixed in your repo the next day, he would have noticed you...

No, don't worry, he's not so spiritual :)

**Comment by gadicc** [comment]
Oh, this last message was quite enlightening :>  You have two different versions of messageformat installed in the same project, one (in `project/packages/messageformat`) is an old version installed via `mrt`, and one properly via the Meteor Packaing System, although you seem to also have an errant symlink in `project/packages/gadicohen:messageformat` pointing to a non-existent directory).  I think if you remove all of these, and just rely on the packaging system, everything will work as expected.

And maybe I'm the spiritual one :)

**Comment by Ebernhaut** [comment]
I had the same problem, that mf_extract didn't work with the error message: 

```
path.js:233
      throw new TypeError('Arguments to path.join must be strings');
            ^
TypeError: Arguments to path.join must be strings
    at Object.win32.join (path.js:233:13)
    at Object.<anonymous> (C:\Users\Elias\AppData\Roaming\npm\node_modules\meteor-messageformat\mf_extract_wrapper.js:52:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

I fixed this issue for me locally. I use windows and there is no environment variable process.env.HOME defined as asked for in mf_extract_wrapper.js.

Since the gadicohen:messageformat meteor package gets installed in the local appdata on windows, the correct path is found by process.env.LOCALAPPDATA.
I implemented this as an additional method in mf_extract_wrapper.js:

```
function getUserHome() {
  return process.env[(process.platform == 'win32') ? 'LOCALAPPDATA' : 'HOME'];
}
```

and changed the code from line 50 as follows:

```
for (name, i=0; i < possibleNames.length; i++) {
  name = possibleNames[i];
  dirName = name.replace(/:/, '_');
  home = getUserHome();
  if (versions[name]) {
    // only first dirname???
    cliPath = path.join(home, '.meteor', 'packages', dirName,
      'Test', 'os', 'packages', name, 'cli', 'mf_extract.js');
    npmBuild = path.join(home, '.meteor', 'packages', dirName,
      versions[name], 'npm', 'node_modules');
    // not used that i know of but seems like a safe bet
    if (!fs.existsSync(cliPath)) {
      cliPath = path.join(home, '.meteor', 'packages', dirName,
        versions[name], 'os', 'packages', dirName, 'cli', 'mf_extract.js');
    }
    break;
  }
}
```

I hope you could implement a working solution for windows like this.
And thank you for the great work! :-)

**Comment by gadicc** [comment]
@Ebernhaut, thanks so much for this.  I think you might be our first windows user :)  I should try merge this on the v0 branch, but you should know that we are mostly working just on the v2 branch atm.

mf_extract caused us a lot of problems (mostly due to changes on Meteor's part, which stabilized after Meteor 1.0 of course), so in v2 we decided to scrap it completely and just scan for changes in the background every time a meteor project file changes.  Performance has been great, since it all happens asynchronously in the background.  I'd love to know if it works on windows.

If you have a moment at some point, for a non-production project, maybe you can look at the README in https://github.com/gadicc/meteor-messageformat/tree/v2 which explains some of the changes and some upgrade instructions.

**Comment by tcastelli** [comment]
also trying it from windows now, so will update with any problems with v2 :)
forgetting about mf_extract is really good news :+1:
